language: python
python:
  - "3.6.3"

# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls

# command to run tests
script:
  - pytest --cov=app/

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token

after-success:
  - coveralls
